# Generated by Django 3.1.7 on 2021-03-21 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='date_needed',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
