# Generated by Django 3.1.7 on 2021-03-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
