# Generated by Django 3.1.7 on 2021-03-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_auto_20210322_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
