# Generated by Django 3.1.7 on 2021-03-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0007_donor_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='accepted',
        ),
        migrations.AddField(
            model_name='cause',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
