# Generated by Django 3.1.7 on 2021-03-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_auto_20210322_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
